### ISSUE TITLE
crop crashes

### ISSUE THREAD

**Issue by yanglilizhang** [hnvn/flutter_image_cropper#113] opened 2019-12-14 05:48 UTC
flutter: v1.12.13+hotfix.5
Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference

**Comment by hsangtini** [comment] 2019-12-14 16:10
A PR here https://github.com/hnvn/flutter_image_cropper/pull/111 and waiting for @hnvn apply it.

**Comment by hnvn** [comment] 2019-12-15 03:46
I can't reproduce the issue in the [example](https://github.com/hnvn/flutter_image_cropper/tree/master/example) project

**Comment by praveenguru** [comment] 2019-12-15 09:25
I'm also having this issue after upgrading flutter

**Comment by hsangtini** [comment] 2019-12-15 16:27
> I can't reproduce the issue in the [example](https://github.com/hnvn/flutter_image_cropper/tree/master/example) project

Did you upgraded latest flutter stable version? Try to open, pick image, crop, then click done icon at top right appbar.

**Comment by hnvn** [comment] 2019-12-16 01:48
I run on Flutter v1.12.13+hotfix.5

**Comment by yanglilizhang** [comment] 2019-12-16 01:52
Try update to image_picker: 0.6.2+1

**Comment by hnvn** [comment] 2019-12-16 14:36
Try again with image_picker 0.6.2+3 and still cannot reproduce the issue

**Comment by lastingman** [comment] 2019-12-16 18:13
same issue here on image_picker 0.6.2+3, image_crop 1.1.1, flutter 1.12.13+hotfix.5

**Comment by luizhcardim** [comment] 2019-12-16 19:18
Same issue here. The problem started after I updated to last version of flutter (v1.12.13+hotfix.5)

**Comment by RodolfoSilva** [comment] 2019-12-17 00:26
I've the same issue

```


12-16 21:22:39.234  5624  5777 I BitmapCropTask: Should crop: true
12-16 21:22:39.238  1389  1409 W audio_hw_generic: Not supplying enough data to HAL, expected position 9896620 , only wrote 9896400
12-16 21:22:39.297  5624  5624 D AndroidRuntime: Shutting down VM
12-16 21:22:39.297  5624  5624 E AndroidRuntime: FATAL EXCEPTION: main
12-16 21:22:39.297  5624  5624 E AndroidRuntime: Process: com.example.crop_with_error, PID: 5624
12-16 21:22:39.297  5624  5624 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=-1, data=Intent { (has extras) }} to activity {com.example.crop_with_error/com.example.crop_with_error.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.app.ActivityThread.-wrap20(ActivityThread.java)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6077)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
12-16 21:22:39.297  5624  5624 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.finishWithSuccess(ImageCropperDelegate.java:110)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:94)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:6915)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
12-16 21:22:39.297  5624  5624 E AndroidRuntime:        ... 9 more
12-16 21:22:39.299  1630  2065 W ActivityManager:   Force finishing activity com.example.crop_with_error/.MainActivity
12-16 21:22:39.327  1630  1671 I OpenGLRenderer: Initialized EGL, version 1.4
12-16 21:22:39.327  1630  1671 D OpenGLRenderer: Swap behavior 1
12-16 21:22:39.327  1630  1671 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
12-16 21:22:39.327  1630  1671 D OpenGLRenderer: Swap behavior 0
12-16 21:22:39.333  1630  1671 D EGL_emulation: eglCreateContext: 0xb65856c0: maj 2 min 0 rcv 2
12-16 21:22:39.354  1630  1671 D EGL_emulation: eglMakeCurrent: 0xb65856c0: ver 2 0 (tinfo 0xb6583680)
12-16 21:22:39.360  1630  1671 D EGL_emulation: eglMakeCurrent: 0xb65856c0: ver 2 0 (tinfo 0xb6583680)
12-16 21:22:39.805  1630  1643 W ActivityManager: Activity pause timeout for ActivityRecord{c5f5726 u0 com.example.crop_with_error/.MainActivity t94 f}
12-16 21:22:39.909  2068  2171 D EGL_emulation: eglMakeCurrent: 0xb6585300: ver 2 0 (tinfo 0xb65832f0)
12-16 21:22:40.214  1630  1643 I ActivityManager: Killing 4390:com.android.camera2/u0a34 (adj 906): empty #17
12-16 21:22:40.218  1630  2097 D GraphicsStats: Buffer count: 5
12-16 21:22:40.219  1630  1640 D ActivityManager: cleanUpApplicationRecord -- 4390
12-16 21:22:40.428  2068  2171 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
12-16 21:22:42.435  1389  1410 W audio_hw_generic: Not supplying enough data to HAL, expected position 10201213 , only wrote 10049760
12-16 21:22:50.219  1630  1643 W ActivityManager: Activity destroy timeout for ActivityRecord{c5f5726 u0 com.example.crop_with_error/.MainActivity t94 f}
12-16 21:22:50.243  1630  1643 W ActivityManager: Activity destroy timeout for ActivityRecord{b7812b3 u0 com.example.crop_with_error/com.yalantis.ucrop.UCropActivity t94 f}
12-16 21:22:50.243  1630  1643 I WindowManager: Destroying surface Surface(name=com.example.crop_with_error/com.yalantis.ucrop.UCropActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2016 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:882 com.android.server.wm.WindowState.removeLocked:1456 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2484 com.android.server.wm.WindowManagerService.removeWindowLocked:2442 com.android.server.wm.WindowManagerService.removeWindowLocked:2311 com.android.server.wm.AppWindowToken.removeAllWindows:530 com.android.server.wm.AppWindowToken.removeAppFromTaskLocked:326 
`
``

**Comment by RodolfoSilva** [comment] 2019-12-17 00:38
The error occurs when call this function:
https://github.com/hnvn/flutter_image_cropper/blob/b816251435271db83b2e0fff402f40e7b8591bd6/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperDelegate.java#L110

Maybe the pendingResult is receiving null as value;

@hnvn

**Comment by hnvn** [comment] 2019-12-17 01:57
Thanks for your feedback. I still look at this issue but I cannot reproduce it on the [example ](https://github.com/hnvn/flutter_image_cropper/tree/master/example) project. Can anyone confirm that it occurs on the example project or only on your real project?

**Comment by RodolfoSilva** [comment] 2019-12-17 01:58
@hnvn I'll test now.

**Comment by RodolfoSilva** [comment] 2019-12-17 02:08
@hnvn I've tested the example app here and the error not appears.  But in my case, I've update the flutter and becouse of this update I've to recreate the android directory. In the new version of flutter scaffold android app I've a Kotlin file and a diferente class to register the plugins.

**Comment by hnvn** [comment] 2019-12-17 02:09
Can you give me a repository to reproduce the issue?

**Comment by RodolfoSilva** [comment] 2019-12-17 02:10
I'll generate here. One moment.

**Comment by RodolfoSilva** [comment] 2019-12-17 02:23
@hnvn https://github.com/RodolfoSilva/flutter_image_cropper/tree/update-example

**Comment by hnvn** [comment] 2019-12-17 02:24
OK, I will look at it and get back to you soon.

**Comment by oppenheimermd** [comment] 2019-12-17 16:51
The example(https://github.com/hnvn/flutter_image_cropper/tree/master/example) does not include image_cropper package in the pubspec.yaml(https://github.com/hnvn/flutter_image_cropper/blob/master/example/pubspec.yaml) file?? When it is added, the app crashes.

**Comment by RodolfoSilva** [comment] 2019-12-17 16:53
@oppenheimermd here: https://github.com/hnvn/flutter_image_cropper/blob/master/example/pubspec.yaml#L26

```yaml
  image_cropper:
    path: ../
```

**Comment by oppenheimermd** [comment] 2019-12-17 16:57
> @oppenheimermd here: https://github.com/hnvn/flutter_image_cropper/blob/master/example/pubspec.yaml#L26
> 
> ```yaml
>   image_cropper:
>     path: ../
> ```

That does not work

**Comment by oppenheimermd** [comment] 2019-12-17 16:58
> @oppenheimermd here: https://github.com/hnvn/flutter_image_cropper/blob/master/example/pubspec.yaml#L26
> 
> ```yaml
>   image_cropper:
>     path: ../
> ```

...as I stated @RodolfoSilva that does not work, the app won't compile, and if added it crashes

**Comment by RodolfoSilva** [comment] 2019-12-17 17:02
@oppenheimermd  What's showing in the log?

**Comment by hnvn** [comment] 2019-12-18 01:47
The problem comes from embedding v2 in Android, you can see the differences in the `MainActivity` and `GeneratedPluginRegistrant` class

**Comment by amreniouinnovent** [comment] 2019-12-18 06:34
@hnvn what is v2?

**Comment by hnvn** [comment] 2019-12-18 06:38
https://github.com/flutter/flutter/wiki/Experimental:-Create-Flutter-Plugin

**Comment by hnvn** [comment] 2019-12-18 06:43
I am still studying the document and try to investigate the issue. It might take time because I can only work on it in my spare time.

**Comment by hnvn** [comment] 2019-12-18 16:06
Hey guys, I just found the problem. The new way to register plugins in Flutter 1.12 causes each plugin being registered twice (the one for the foreground and the other for background mode)
```java
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.registerWith(shimPluginRegistry.registrarFor("vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin"));
      io.flutter.plugins.imagepicker.ImagePickerPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.imagepicker.ImagePickerPlugin"));
  }
}
```
It means that there're 2 instances of `ImageCropperDelegate` in runtime. When user clicks on button to start cropping task, one instance is triggered to process input data, when the cropping task is finished, the other instance is triggered to process result data. That's why `pendingResult` variable is null. 

I have just released a new version (1.1.2) to hotfix this issue but it still needs more effort to migrate this plugin to embedding v2 comprehensively. I will create a new issue for it.

**Comment by RodolfoSilva** [comment] 2019-12-18 17:20
I'll test latter. Thanks @hnvn .

**Comment by amorenew** [comment] 2019-12-18 18:25
@hnvn 1.1.2 no crash
well done.

**Comment by RodolfoSilva** [comment] 2019-12-18 22:26
Working like a charm. 😛 . Thanks @hnvn

**Comment by hnvn** [comment] 2019-12-19 01:42
I'm going to close this issue.

**Closed by hnvn** 2019-12-19 01:42 UTC
Labels: bug
