### ISSUE TITLE
Can we have 6 or 8 edge Crop ?

### ISSUE THREAD

**Issue by sumit03111988** [hnvn/flutter_image_cropper#202] opened 2020-09-23 17:05 UTC
Hi,

Your work is wonderful. All works perfectly.

Can you please guide me, how can I implement or modify it to 6-8 edge crop instead of 4 only.

It would be the great help . Thanks in advance

Waiting to hear from you or if you are planning to enhance it. Please let me know.

**Comment by hnvn** [comment] 2020-09-25 10:01
Duplicate of #205

**Closed** 2020-09-25 10:02 UTC
